### ISSUE TITLE
Badge counter not showing on effect bar

### ISSUE THREAD

**Issue by roguedevjake** [Dorako/pf2e-dorako-ui#144]
The 4.7 PF2e update puts the numerical badge overlay in the bottom left hand corner of the effect display. With Dorako turned on this hides it. 

If there is a choice, personally I think the previous large sized centered number was better, the current number is... tiny on a 4k screen.

**Comment by Dorako** [comment]
I fixed the effect value missing in 1.11.8 (regression due to the system change you mentioned).

I don't think Dorako UI has had the value large and centered since the SASS rewrite - I'm leaning towards keeping a similar layout as the system, since adjustments in this area were probably made with future capabilities in mind. (Perhaps afflictions?)
