### ISSUE TITLE
Item 'Send' function has become broken

### ISSUE THREAD

**Issue by WBHarry** [Dorako/pf2e-dorako-ui#161]
Heya. Sending text from an Item to chat doesn't work anymore. I know it didn't work for me prior to the 4.8.0 system update either, since I was playing a session without updating. 😅 
![image](https://user-images.githubusercontent.com/89362246/221065218-09b8c995-0d75-4fe0-ad68-08abbdbc2de2.png)
Easily reproducable by just grabbing a Steel Shield or any other standard item and trying to use 'Send'.

**Comment by Dorako** [comment]
Sadly I think it's time for this functionality to go away. I originally included it despite it not really being a "Dorako UI feature" and more of a Workbench type of feature, because the lines of code needed were so few.
Last time something came up that required rewriting this feature to support more advanced pf2e data I told myself that I'd scrap the feature next time it became broken.
To my knowledge there are at least two modules that do a similar thing (and just that thing) and I imagine that those are better supported.
