### ISSUE TITLE
Support for Dice Stats

### ISSUE THREAD

**Issue by MindWeb125** [Dorako/pf2e-dorako-ui#173]
Hi Dorako!

Would it be possible to implement support for Dice Stats? It's a pretty simple UI but it would be even better with a quality dark theme.

[Dice Stats](https://github.com/jacobwojoski/dice-stats)

![image](https://user-images.githubusercontent.com/105242276/224849005-2aedb6ce-8f9b-407a-9289-bb65daec49fd.png)

**Comment by Dorako** [comment]
It seems to be already activating dark theme
<img width="647" alt="CleanShot 2023-03-14 at 19 17 45@2x" src="https://user-images.githubusercontent.com/1561190/225100469-6be37de0-ba25-43cf-beb1-894b44f98f65.png">
I can't easily recolor the text in the chart, since the color is baked into the chart "graphic", but I can give it a golden background to increase legibility

**Comment by MindWeb125** [comment]
Ah, that's fair, I didn't think about the text being a chart element. 

Changing the background would probably be perfect to be honest.

**Comment by Dorako** [comment]
I made it look like this for next release
<img width="648" alt="CleanShot 2023-03-14 at 19 23 59@2x" src="https://user-images.githubusercontent.com/1561190/225101852-9ae819fc-9c60-4616-8aff-662b1a34451b.png">

**Comment by MindWeb125** [comment]
Awesome, thank you!
