### ISSUE TITLE
Feature Request - Separate Settings By Player

### ISSUE THREAD

**Issue by SoilentBrad** [Dorako/pf2e-dorako-ui#250]
What the title says: it would be great if everyone logging into the game could have their own separate settings. Unless it's possible and I couldn't figure it out, but I tried logging in as one of my players and changing the theme and it changed it for myself when I logged back in as Gamemaster. Especially since one of my players is on mobile - I don't want anything that will make it more difficult for her to log in.

Hopefully it's something you can do, but it's absolutely fine if not.

Thanks

**Comment by Dorako** [comment]
Almost all settings in Dorako UI (except the ones where it doesn't make sense for a player to be able to afjust it) are client settings, rather than world settings.
However, settings in foundry are not stored on the user, but in the browser, so you cannot change the setting for your player (without a module), they have to change it themselves.
