### ISSUE TITLE
Token icons not appearing with secret checks

### ISSUE THREAD

**Issue by grankless** [Dorako/pf2e-dorako-ui#36]
https://i.imgur.com/wBoo0VN.png Token icons aren't appearing when I rol lsecret checks with the appropriate chat card settings enabled, but are on regular rolls.

**Comment by Dorako** [comment]
This is intentional, for cases like hidden monsters rolling initiative, (but the creature art is still visible in the combat tracker I believe, so it'll require some improvements to creature mystification to make perfect sense). In your case the creature isn't mystified, so it seems weird. If it's possible for me to conclude that creature name isn't mystified, I'll see if I can show the image.

**Comment by grankless** [comment]
To be specific, this is on players. Not sure if it's on creatures or not; if it was,  I just didn't notice.

**Comment by Dorako** [comment]
I don't think the current code cares whether it's a player or not. I'm not sure what the behavior should be for a mystified player token, but I'm not sure why you'd ever have that anyway.

**Comment by Dorako** [comment]
I think I'm actually reverting this change - the real solution is that hidden units should roll initiative as blind rolls - that will show the image, but only to gm.
