### ISSUE TITLE
Dorako UI is hiding the delete button if the chat cards are collapsed (DF chat enhancements)

### ISSUE THREAD

**Issue by fraserstanton** [Dorako/pf2e-dorako-ui#81]
![image](https://user-images.githubusercontent.com/85046656/189852880-23812088-d502-48f4-a2cb-3cb6390b1e50.png)

![image](https://user-images.githubusercontent.com/85046656/189852921-8ee4ede0-7c44-4c5c-916c-ba84310879e8.png)

**Comment by Dorako** [comment]
This is a side effect of Dorako UI massively restructuring the 'header' section of chat messages. In this case I don't think I will fix it, as the fix is non-trivial and the 'fixed' behaviour has several downsides as well.
See for example this standard pf2e-system message, and note the offset from the right. With Dorako UI on, this would look even weirder.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/1561190/190018636-03353a91-1f97-4fee-819d-01af1f459672.png">

If you need to delete a message that has been 'collapsed' via DF Chat Enhancements, you can right-click the message and hit 'delete'.

I noticed a bug that cause the context menu to get cut off making this impossible under certain circumstances - I will be fixing this.
